# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bd5676bff2aebfd112c3816c9d9a5720"
application_url = "https://situated-flame-qualities-writer.trycloudflare.com"
embedded = true
name = "wishlist-inspire"
handle = "wishlist-inspire-318"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://situated-flame-qualities-writer.trycloudflare.com/auth/callback",
  "https://situated-flame-qualities-writer.trycloudflare.com/auth/shopify/callback",
  "https://situated-flame-qualities-writer.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "asl-dev-store.myshopify.com"
automatically_update_urls_on_dev = true
